BE-953 add main services
realifetech/api-extension pull request #1
Opened 2021-03-23 17:00 UTC by DashaSyvyuk

2021-03-31 08:40 UTC, tomrutherford-livestyled requested changes

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Entity/ApiKeyAccess.php
> +        'DELETE' => 'DELETE',
This array needs to include PATCH

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/EventBus/EventBridgeClient.php
> +                        'Source' => 'apiv3', // TODO payment
Source needs to change, please use `APP_NAME` from the `.env` file. This should be passed into the constructor like `env`

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/EventListener/EntityPreWriteSubscriber.php
> +    const APP_ID = 27;
Why do we need these?

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/EventListener/EntityPreWriteSubscriber.php
> +        $propertyAccessor->setValue($entity, 'app', self::APP_ID);
Why are we always setting app 27?

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/EventListener/EntityPreWriteSubscriber.php
> +        $propertyAccessor->setValue($entity, 'tenant', self::TENANT_ID);
same here

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Routing/IriConverter.php
> +                'LS\ApiBundle\Annotation\MicroserviceAware'
I think this namespace is now incorrect

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Security/Configurator/Configurator.php
> +                $filter->setParameter('currentApp', self::CURRENT_APP);
Why are we always setting 27?

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Security/Extension/AppFilterExtension.php
> +        $filter->setParameter('currentApp', self::DEFAULT_APP);
same here

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Validator/Translations.php
> +}
need new line

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on composer.json
> +        "api-platform/api-pack": "^1.3",
Do we need Api Platform?

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on composer.json
> +        "symfony/symfony": "^5.2",
Symfony:4.4

2021-03-31 08:40 UTC, tomrutherford-livestyled commented on src/Entity/ApiKey.php
> +    private int $app;
Should be $tenant

2021-03-31 15:54 UTC, DashaSyvyuk commented on composer.json
> +        "api-platform/api-pack": "^1.3",
we use it for IRI

2021-04-01 12:51 UTC, tomrutherford-livestyled requested changes

2021-04-01 12:51 UTC, tomrutherford-livestyled commented on src/EventBus/EventBridgeClient.php
> +                        'Source' => $this->env,
This should be the application name. We need another parameter in the constructor named `$source` and it should be set from the Symfont env variable `APP_NAME`

2021-04-01 12:51 UTC, tomrutherford-livestyled commented on src/Provider/TenantProvider.php
> +        //pass
Maybe we should throw an exception here

2021-04-01 12:51 UTC, tomrutherford-livestyled commented on src/Provider/TenantProvider.php
> +    public function refreshUser(UserInterface $user)
and here

2021-04-01 12:51 UTC, tomrutherford-livestyled commented on src/Provider/TenantProvider.php
> +    public function supportsClass($class)
and here

2021-04-01 12:51 UTC, tomrutherford-livestyled commented on src/Security/Filter/TenantFilter.php
> +            $fieldName = 'app_id';
should probably add a check for this field as well instead of assuming it's always there if `tenant` isnt

2021-04-06 08:45 UTC, tomrutherford-livestyled approved these changes

2021-04-06 08:58 UTC, merged